// This file is automatically generated
// Do not edit

#include "rs-unicode/property-list.hpp"

namespace RS::Unicode {

    bool is_pattern_white_space(char32_t c) {

        static const BinaryPropertyMap map {

            { 0x9, 0xd },
            { 0x20, 0x20 },
            { 0x85, 0x85 },
            { 0x200e, 0x200f },
            { 0x2028, 0x2029 },

        };

        return map[c];

    }

}
