// This file is automatically generated
// Do not edit

#include "rs-unicode/property-list.hpp"
#include <array>
#include <string_view>
#include <unordered_map>

namespace RS::Unicode {

    const std::array<std::u32string_view, 3>& special_casing(char32_t c) {

        static const std::unordered_map<char32_t, std::array<std::u32string_view, 3>> map {

            { 0xdf, { U"\u00df", U"\u0053\u0073", U"\u0053\u0053" } },
            { 0x130, { U"\u0069\u0307", U"\u0130", U"\u0130" } },
            { 0x149, { U"\u0149", U"\u02bc\u004e", U"\u02bc\u004e" } },
            { 0x1f0, { U"\u01f0", U"\u004a\u030c", U"\u004a\u030c" } },
            { 0x390, { U"\u0390", U"\u0399\u0308\u0301", U"\u0399\u0308\u0301" } },
            { 0x3b0, { U"\u03b0", U"\u03a5\u0308\u0301", U"\u03a5\u0308\u0301" } },
            { 0x587, { U"\u0587", U"\u0535\u0582", U"\u0535\u0552" } },
            { 0x1e96, { U"\u1e96", U"\u0048\u0331", U"\u0048\u0331" } },
            { 0x1e97, { U"\u1e97", U"\u0054\u0308", U"\u0054\u0308" } },
            { 0x1e98, { U"\u1e98", U"\u0057\u030a", U"\u0057\u030a" } },
            { 0x1e99, { U"\u1e99", U"\u0059\u030a", U"\u0059\u030a" } },
            { 0x1e9a, { U"\u1e9a", U"\u0041\u02be", U"\u0041\u02be" } },
            { 0x1f50, { U"\u1f50", U"\u03a5\u0313", U"\u03a5\u0313" } },
            { 0x1f52, { U"\u1f52", U"\u03a5\u0313\u0300", U"\u03a5\u0313\u0300" } },
            { 0x1f54, { U"\u1f54", U"\u03a5\u0313\u0301", U"\u03a5\u0313\u0301" } },
            { 0x1f56, { U"\u1f56", U"\u03a5\u0313\u0342", U"\u03a5\u0313\u0342" } },
            { 0x1f80, { U"\u1f80", U"\u1f88", U"\u1f08\u0399" } },
            { 0x1f81, { U"\u1f81", U"\u1f89", U"\u1f09\u0399" } },
            { 0x1f82, { U"\u1f82", U"\u1f8a", U"\u1f0a\u0399" } },
            { 0x1f83, { U"\u1f83", U"\u1f8b", U"\u1f0b\u0399" } },
            { 0x1f84, { U"\u1f84", U"\u1f8c", U"\u1f0c\u0399" } },
            { 0x1f85, { U"\u1f85", U"\u1f8d", U"\u1f0d\u0399" } },
            { 0x1f86, { U"\u1f86", U"\u1f8e", U"\u1f0e\u0399" } },
            { 0x1f87, { U"\u1f87", U"\u1f8f", U"\u1f0f\u0399" } },
            { 0x1f88, { U"\u1f80", U"\u1f88", U"\u1f08\u0399" } },
            { 0x1f89, { U"\u1f81", U"\u1f89", U"\u1f09\u0399" } },
            { 0x1f8a, { U"\u1f82", U"\u1f8a", U"\u1f0a\u0399" } },
            { 0x1f8b, { U"\u1f83", U"\u1f8b", U"\u1f0b\u0399" } },
            { 0x1f8c, { U"\u1f84", U"\u1f8c", U"\u1f0c\u0399" } },
            { 0x1f8d, { U"\u1f85", U"\u1f8d", U"\u1f0d\u0399" } },
            { 0x1f8e, { U"\u1f86", U"\u1f8e", U"\u1f0e\u0399" } },
            { 0x1f8f, { U"\u1f87", U"\u1f8f", U"\u1f0f\u0399" } },
            { 0x1f90, { U"\u1f90", U"\u1f98", U"\u1f28\u0399" } },
            { 0x1f91, { U"\u1f91", U"\u1f99", U"\u1f29\u0399" } },
            { 0x1f92, { U"\u1f92", U"\u1f9a", U"\u1f2a\u0399" } },
            { 0x1f93, { U"\u1f93", U"\u1f9b", U"\u1f2b\u0399" } },
            { 0x1f94, { U"\u1f94", U"\u1f9c", U"\u1f2c\u0399" } },
            { 0x1f95, { U"\u1f95", U"\u1f9d", U"\u1f2d\u0399" } },
            { 0x1f96, { U"\u1f96", U"\u1f9e", U"\u1f2e\u0399" } },
            { 0x1f97, { U"\u1f97", U"\u1f9f", U"\u1f2f\u0399" } },
            { 0x1f98, { U"\u1f90", U"\u1f98", U"\u1f28\u0399" } },
            { 0x1f99, { U"\u1f91", U"\u1f99", U"\u1f29\u0399" } },
            { 0x1f9a, { U"\u1f92", U"\u1f9a", U"\u1f2a\u0399" } },
            { 0x1f9b, { U"\u1f93", U"\u1f9b", U"\u1f2b\u0399" } },
            { 0x1f9c, { U"\u1f94", U"\u1f9c", U"\u1f2c\u0399" } },
            { 0x1f9d, { U"\u1f95", U"\u1f9d", U"\u1f2d\u0399" } },
            { 0x1f9e, { U"\u1f96", U"\u1f9e", U"\u1f2e\u0399" } },
            { 0x1f9f, { U"\u1f97", U"\u1f9f", U"\u1f2f\u0399" } },
            { 0x1fa0, { U"\u1fa0", U"\u1fa8", U"\u1f68\u0399" } },
            { 0x1fa1, { U"\u1fa1", U"\u1fa9", U"\u1f69\u0399" } },
            { 0x1fa2, { U"\u1fa2", U"\u1faa", U"\u1f6a\u0399" } },
            { 0x1fa3, { U"\u1fa3", U"\u1fab", U"\u1f6b\u0399" } },
            { 0x1fa4, { U"\u1fa4", U"\u1fac", U"\u1f6c\u0399" } },
            { 0x1fa5, { U"\u1fa5", U"\u1fad", U"\u1f6d\u0399" } },
            { 0x1fa6, { U"\u1fa6", U"\u1fae", U"\u1f6e\u0399" } },
            { 0x1fa7, { U"\u1fa7", U"\u1faf", U"\u1f6f\u0399" } },
            { 0x1fa8, { U"\u1fa0", U"\u1fa8", U"\u1f68\u0399" } },
            { 0x1fa9, { U"\u1fa1", U"\u1fa9", U"\u1f69\u0399" } },
            { 0x1faa, { U"\u1fa2", U"\u1faa", U"\u1f6a\u0399" } },
            { 0x1fab, { U"\u1fa3", U"\u1fab", U"\u1f6b\u0399" } },
            { 0x1fac, { U"\u1fa4", U"\u1fac", U"\u1f6c\u0399" } },
            { 0x1fad, { U"\u1fa5", U"\u1fad", U"\u1f6d\u0399" } },
            { 0x1fae, { U"\u1fa6", U"\u1fae", U"\u1f6e\u0399" } },
            { 0x1faf, { U"\u1fa7", U"\u1faf", U"\u1f6f\u0399" } },
            { 0x1fb2, { U"\u1fb2", U"\u1fba\u0345", U"\u1fba\u0399" } },
            { 0x1fb3, { U"\u1fb3", U"\u1fbc", U"\u0391\u0399" } },
            { 0x1fb4, { U"\u1fb4", U"\u0386\u0345", U"\u0386\u0399" } },
            { 0x1fb6, { U"\u1fb6", U"\u0391\u0342", U"\u0391\u0342" } },
            { 0x1fb7, { U"\u1fb7", U"\u0391\u0342\u0345", U"\u0391\u0342\u0399" } },
            { 0x1fbc, { U"\u1fb3", U"\u1fbc", U"\u0391\u0399" } },
            { 0x1fc2, { U"\u1fc2", U"\u1fca\u0345", U"\u1fca\u0399" } },
            { 0x1fc3, { U"\u1fc3", U"\u1fcc", U"\u0397\u0399" } },
            { 0x1fc4, { U"\u1fc4", U"\u0389\u0345", U"\u0389\u0399" } },
            { 0x1fc6, { U"\u1fc6", U"\u0397\u0342", U"\u0397\u0342" } },
            { 0x1fc7, { U"\u1fc7", U"\u0397\u0342\u0345", U"\u0397\u0342\u0399" } },
            { 0x1fcc, { U"\u1fc3", U"\u1fcc", U"\u0397\u0399" } },
            { 0x1fd2, { U"\u1fd2", U"\u0399\u0308\u0300", U"\u0399\u0308\u0300" } },
            { 0x1fd3, { U"\u1fd3", U"\u0399\u0308\u0301", U"\u0399\u0308\u0301" } },
            { 0x1fd6, { U"\u1fd6", U"\u0399\u0342", U"\u0399\u0342" } },
            { 0x1fd7, { U"\u1fd7", U"\u0399\u0308\u0342", U"\u0399\u0308\u0342" } },
            { 0x1fe2, { U"\u1fe2", U"\u03a5\u0308\u0300", U"\u03a5\u0308\u0300" } },
            { 0x1fe3, { U"\u1fe3", U"\u03a5\u0308\u0301", U"\u03a5\u0308\u0301" } },
            { 0x1fe4, { U"\u1fe4", U"\u03a1\u0313", U"\u03a1\u0313" } },
            { 0x1fe6, { U"\u1fe6", U"\u03a5\u0342", U"\u03a5\u0342" } },
            { 0x1fe7, { U"\u1fe7", U"\u03a5\u0308\u0342", U"\u03a5\u0308\u0342" } },
            { 0x1ff2, { U"\u1ff2", U"\u1ffa\u0345", U"\u1ffa\u0399" } },
            { 0x1ff3, { U"\u1ff3", U"\u1ffc", U"\u03a9\u0399" } },
            { 0x1ff4, { U"\u1ff4", U"\u038f\u0345", U"\u038f\u0399" } },
            { 0x1ff6, { U"\u1ff6", U"\u03a9\u0342", U"\u03a9\u0342" } },
            { 0x1ff7, { U"\u1ff7", U"\u03a9\u0342\u0345", U"\u03a9\u0342\u0399" } },
            { 0x1ffc, { U"\u1ff3", U"\u1ffc", U"\u03a9\u0399" } },
            { 0xfb00, { U"\ufb00", U"\u0046\u0066", U"\u0046\u0046" } },
            { 0xfb01, { U"\ufb01", U"\u0046\u0069", U"\u0046\u0049" } },
            { 0xfb02, { U"\ufb02", U"\u0046\u006c", U"\u0046\u004c" } },
            { 0xfb03, { U"\ufb03", U"\u0046\u0066\u0069", U"\u0046\u0046\u0049" } },
            { 0xfb04, { U"\ufb04", U"\u0046\u0066\u006c", U"\u0046\u0046\u004c" } },
            { 0xfb05, { U"\ufb05", U"\u0053\u0074", U"\u0053\u0054" } },
            { 0xfb06, { U"\ufb06", U"\u0053\u0074", U"\u0053\u0054" } },
            { 0xfb13, { U"\ufb13", U"\u0544\u0576", U"\u0544\u0546" } },
            { 0xfb14, { U"\ufb14", U"\u0544\u0565", U"\u0544\u0535" } },
            { 0xfb15, { U"\ufb15", U"\u0544\u056b", U"\u0544\u053b" } },
            { 0xfb16, { U"\ufb16", U"\u054e\u0576", U"\u054e\u0546" } },
            { 0xfb17, { U"\ufb17", U"\u0544\u056d", U"\u0544\u053d" } },

        };

        static const std::array<std::u32string_view, 3> empty;

        auto it = map.find(c);

        if (it == map.end()) {
            return empty;
        } else {
            return it->second;
        }

    }

}
