// This file is automatically generated
// Do not edit

#include "rs-unicode/property-list.hpp"

namespace RS::Unicode {

    bool is_id_compat_math_continue(char32_t c) {

        static const BinaryPropertyMap map {

            { 0xb2, 0xb3 },
            { 0xb9, 0xb9 },
            { 0x2070, 0x2070 },
            { 0x2074, 0x207e },
            { 0x2080, 0x208e },
            { 0x2202, 0x2202 },
            { 0x2207, 0x2207 },
            { 0x221e, 0x221e },
            { 0x1d6c1, 0x1d6c1 },
            { 0x1d6db, 0x1d6db },
            { 0x1d6fb, 0x1d6fb },
            { 0x1d715, 0x1d715 },
            { 0x1d735, 0x1d735 },
            { 0x1d74f, 0x1d74f },
            { 0x1d76f, 0x1d76f },
            { 0x1d789, 0x1d789 },
            { 0x1d7a9, 0x1d7a9 },
            { 0x1d7c3, 0x1d7c3 },

        };

        return map[c];

    }

}
