// This file is automatically generated
// Do not edit

#include "rs-unicode/property-list.hpp"

namespace RS::Unicode {

    bool is_white_space(char32_t c) {

        static const BinaryPropertyMap map {

            { 0x9, 0xd },
            { 0x20, 0x20 },
            { 0x85, 0x85 },
            { 0xa0, 0xa0 },
            { 0x1680, 0x1680 },
            { 0x2000, 0x200a },
            { 0x2028, 0x2029 },
            { 0x202f, 0x202f },
            { 0x205f, 0x205f },
            { 0x3000, 0x3000 },

        };

        return map[c];

    }

}
